version: '3.9'

services:
  # MongoDB service 
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db 

  # Node API service
  api: 
    container_name: api_container
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    environment:
      LEETCODE_GRAPHQL_ENDPOINT: https://leetcode.com/graphql
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: leetcode-stats
      PORT: 8000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
